# Generated by Django 3.2.12 on 2022-03-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='global', max_length=300),
        ),
    ]
