# Generated by Django 4.0.3 on 2022-03-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_comment_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
